/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.conectar;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Colegio Antropologos
 */
public class Menu_principal extends javax.swing.JFrame {
 conectar cc = new conectar();
 Connection cn = cc.conexion();
 
    public Menu_principal() {
        initComponents();
        setLocationRelativeTo(this);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logg.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuRegistrar = new javax.swing.JMenuItem();
        menuPago = new javax.swing.JMenuItem();
        MenuCon = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menulista = new javax.swing.JMenuItem();
        menulistapago = new javax.swing.JMenuItem();
        menulistahabiltados = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuControl = new javax.swing.JMenuItem();
        menuPatron = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        manuUsuario = new javax.swing.JMenuItem();
        menuContacto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prueba2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(0, 255, 255));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-casa-48.png"))); // NOI18N
        jMenu2.setText("Inicio");
        jMenu2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Businessman_48px.png"))); // NOI18N
        jMenuItem11.setText("Iniciar Sesión");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        menuSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-cerrar-ventana-48.png"))); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(menuSalir);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Add User Male_48px.png"))); // NOI18N
        jMenu1.setText("Registro");
        jMenu1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        menuRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-añadir-usuario-grupo-mujer-hombre-48.png"))); // NOI18N
        menuRegistrar.setText("Registro Usuario");
        menuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(menuRegistrar);

        menuPago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Paper Money_48px.png"))); // NOI18N
        menuPago.setText("Registro de Pago");
        menuPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagoActionPerformed(evt);
            }
        });
        jMenu1.add(menuPago);

        MenuCon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MenuCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Tick Box_48px.png"))); // NOI18N
        MenuCon.setText("Registro de Habilitación");
        MenuCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConActionPerformed(evt);
            }
        });
        jMenu1.add(MenuCon);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Search_48px.png"))); // NOI18N
        jMenu4.setText("Consulta");
        jMenu4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        menulista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menulista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Contacts_48px.png"))); // NOI18N
        menulista.setText("Lista de Patrón General");
        menulista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulistaActionPerformed(evt);
            }
        });
        jMenu4.add(menulista);

        menulistapago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menulistapago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Bank_48px.png"))); // NOI18N
        menulistapago.setText("Lista de Pago");
        menulistapago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulistapagoActionPerformed(evt);
            }
        });
        jMenu4.add(menulistapago);

        menulistahabiltados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menulistahabiltados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Conference_48px.png"))); // NOI18N
        menulistahabiltados.setText("Lista de Habilitaciones");
        menulistahabiltados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulistahabiltadosActionPerformed(evt);
            }
        });
        jMenu4.add(menulistahabiltados);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-carpeta-48.png"))); // NOI18N
        jMenu5.setText("Reportes");
        jMenu5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        menuControl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuControl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Document_48px.png"))); // NOI18N
        menuControl.setText("Reporte de Habilitación");
        menuControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControlActionPerformed(evt);
            }
        });
        jMenu5.add(menuControl);

        menuPatron.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuPatron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Survey_48px.png"))); // NOI18N
        menuPatron.setText("Reporte de Patrón General");
        menuPatron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatronActionPerformed(evt);
            }
        });
        jMenu5.add(menuPatron);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Report Card_48px.png"))); // NOI18N
        jMenuItem1.setText("Reporte de Pago");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8-ajustes-48.png"))); // NOI18N
        jMenu6.setText("Ayuda");
        jMenu6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        manuUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/PDF_48px.png"))); // NOI18N
        manuUsuario.setText("Manual de Usuario");
        manuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(manuUsuario);

        menuContacto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Maintenance_48px.png"))); // NOI18N
        menuContacto.setText("Contacto");
        menuContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContactoActionPerformed(evt);
            }
        });
        jMenu6.add(menuContacto);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnHabilitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitacionActionPerformed
        
    }//GEN-LAST:event_btnHabilitacionActionPerformed

    private void btnControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlActionPerformed
       

    }//GEN-LAST:event_btnControlActionPerformed

    private void btnconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconectarActionPerformed
        
    }//GEN-LAST:event_btnconectarActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Login lo = new Login();
        this.setVisible(false);
        lo.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void menulistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulistaActionPerformed
        patron pa = new patron();
        this.setVisible(true);
        pa.setVisible(true);
    }//GEN-LAST:event_menulistaActionPerformed

    private void menulistahabiltadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulistahabiltadosActionPerformed
         habilitacion hab =new habilitacion();
         this.setVisible(true);
         hab.setVisible(true);
    }//GEN-LAST:event_menulistahabiltadosActionPerformed

    private void menuControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControlActionPerformed
        JasperReport reporte; //Creo el objeto reporte
         // Ubicacion del Reporte
        String path = "src\\Reportes\\rcontrol.jasper";
        try {
            
            //JasperReport jasperReport = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rcontrol.jasper"));
            //reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Cargo el reporte al objeto
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rcontrol.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint,false); //Creamos la vista del Reporte
             viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex) {
            Logger.getLogger(patron.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuControlActionPerformed

    private void menuPatronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatronActionPerformed
        JasperReport reporte; //Creo el objeto reporte
         // Ubicacion del Reporte
        String path = "src\\Reportes\\rpatron.jasper";
        try {
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rpatron.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint,false); //Creamos la vista del Reporte
             viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex) {
            Logger.getLogger(patron.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuPatronActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContactoActionPerformed
        contacto con = new contacto();
        this.setVisible(true);
        con.setVisible(true);
    }//GEN-LAST:event_menuContactoActionPerformed

    private void menulistapagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulistapagoActionPerformed
        registropago reg =new registropago();
        this.setVisible(true);
        reg.setVisible(true);
    }//GEN-LAST:event_menulistapagoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          JasperReport reporte; //Creo el objeto reporte
         // Ubicacion del Reporte
        String path = "src\\Reportes\\rpago.jasper";
        try {
            reporte = (JasperReport) JRLoader.loadObject(getClass().getResource("/Reportes/rpago.jasper"));
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, cn); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint,false); //Creamos la vista del Reporte
             viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
        } catch (JRException ex) {
            Logger.getLogger(patron.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistrarActionPerformed
        registro re = new registro();
        this.setVisible(true);
        re.setVisible(true);
    }//GEN-LAST:event_menuRegistrarActionPerformed

    private void menuPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagoActionPerformed
        pago p =new pago();
        this.setVisible(true);
        p.setVisible(true);
    }//GEN-LAST:event_menuPagoActionPerformed

    private void MenuConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConActionPerformed
       control contr =new control();
       this.setVisible(true);
       contr.setVisible(true);
    }//GEN-LAST:event_MenuConActionPerformed

    private void manuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuUsuarioActionPerformed
        manual manu =new manual();
        this.setVisible(true);
        manu.setVisible(true);
    }//GEN-LAST:event_manuUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem manuUsuario;
    private javax.swing.JMenuItem menuContacto;
    private javax.swing.JMenuItem menuControl;
    private javax.swing.JMenuItem menuPago;
    private javax.swing.JMenuItem menuPatron;
    private javax.swing.JMenuItem menuRegistrar;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menulista;
    private javax.swing.JMenuItem menulistahabiltados;
    private javax.swing.JMenuItem menulistapago;
    // End of variables declaration//GEN-END:variables
}
